## Application: Illustrating the use of the package by imputing the race of the campaign contributors recorded by FEC for the years 2000 and 2010

    a) what proportion of contributors were black, whites, hispanics, asian etc.
    b) and proportion of total donation given by blacks, hispanics, whites, and asians.  
    c) get amount contributed by people of each race and divide it by total amount contributed.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/opt/names/fec_contrib/contribDB_2000.csv', nrows=100)
df.columns

Index([u'cycle', u'transaction_id', u'transaction_type', u'amount', u'date',
       u'bonica_cid', u'contributor_name', u'contributor_lname',
       u'contributor_fname', u'contributor_mname', u'contributor_suffix',
       u'contributor_title', u'contributor_ffname', u'contributor_type',
       u'contributor_gender', u'contributor_address', u'contributor_city',
       u'contributor_state', u'contributor_zipcode', u'contributor_occupation',
       u'contributor_employer', u'contributor_category',
       u'contributor_category_order', u'is_corp', u'organization_name',
       u'parent_organization_name', u'recipient_name', u'bonica_rid',
       u'recipient_party', u'recipient_type', u'recipient_state',
       u'recipient_category', u'recipient_category_order',
       u'recipient_district', u'seat', u'election_type',
       u'contributor_cfscore', u'candidate_cfscore', u'latitude', u'longitude',
       u'gis_confidence', u'contributor_district_90s',
       u'contributor_district_00s', u'contributor_district_10s',
       u'lname_frequency', u'efec_memo', u'efec_memo2',
       u'efec_transaction_id_orig', u'efec_org_orig', u'efec_comid_orig',
       u'efec_form_type'],
      dtype='object')

amount, date, contributor_name, contributor_lname, contributor_fname, contributor_type == 'I'

In [3]:
#df = pd.read_csv('/opt/names/fec_contrib/contribDB_2000.csv', usecols=['date', 'amount', 'contributor_type', 'contributor_lname', 'contributor_fname', 'contributor_name'], nrows=300000)
df = pd.read_csv('/opt/names/fec_contrib/contribDB_2000.csv', usecols=['date', 'amount', 'contributor_type', 'contributor_lname', 'contributor_fname', 'contributor_name'])
df

/opt/venv/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,amount,date,contributor_name,contributor_lname,contributor_fname,contributor_type
0,0.0,2000-04-12,AMERICAN COUNCIL OF LIFE INSURANCE POLITICAL A...,NaN,NaN,C
1,0.0,2000-08-01,NATIONAL ASSOCIATION OF WHEAT GROWERS POLITICA...,NaN,NaN,C
2,0.0,2000-08-01,NATIONAL ASSOCIATION OF WHEAT GROWERS POLITICA...,NaN,NaN,C
3,1.0,2000-09-12,AMERICAN OCCUPATIONAL THERAPY POLITICAL ACTION...,NaN,NaN,C
4,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
5,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
6,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
7,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
8,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
9,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
10,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
11,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
12,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
13,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
14,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
15,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
16,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
17,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
18,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
19,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
20,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
21,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
22,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
23,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
24,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
25,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
26,1.0,2000-09-30,UNITED NATIONS REFORM ELECTORAL CAMPAIGN COMMI...,NaN,NaN,C
27,1.0,2000-09-01,NEW DEMOCRAT NETWORK,NaN,NaN,C
28,1.0,2000-06-07,MOVEON.ORG,NaN,NaN,C
29,3.0,2000-07-10,NATIONAL JEWISH DEMOCRATIC COUNCIL POLITICAL A...,NaN,NaN,C
...,...,...,...,...,...,...
4558246,50.0,1999-04-01,"wu, brian",wu,brian,I
4558247,150.0,1999-10-19,"wu, brian w",wu,brian,I
4558248,50.0,1999-09-22,"wyne, jamshad",wyne,jamshad,I
4558249,250.0,1999-10-20,"yaghoubi, mehrdad",yaghoubi,mehrdad,I
4558250,50.0,1999-10-23,"yassky, prof david",yassky,prof,I
4558251,50.0,1999-08-31,"yeger, eli",yeger,eli,I
4558252,125.0,1999-08-31,"yeger, itamar",yeger,itamar,I
4558253,25.0,1999-08-31,"yeger, shalom",yeger,shalom,I
4558254,20.0,1999-11-03,"yellin, gene",yellin,gene,I
4558255,50.0,1999-11-04,"yen, shawna",yen,shawna,I
4558256,70.0,1999-09-18,"yennella, maryann",yennella,maryann,I
4558257,50.0,1999-04-05,"yennella, maryann",yennella,maryann,I
4558258,100.0,1999-03-19,"yeres, jeffrey d",yeres,jeffrey,I
4558259,50.0,1999-09-22,"yost, glenn",yost,glenn,I
4558260,25.0,1999-09-21,"zacharius, alice",zacharius,alice,I
4558261,35.0,1999-10-19,"zalk, sue r",zalk,sue,I
4558262,100.0,1999-10-04,"zarin, judith ellen",zarin,judith,I
4558263,100.0,1999-10-30,"zimmer, peter k",zimmer,peter,I
4558264,75.0,1999-07-16,"zimmerman, jonathan l",zimmerman,jonathan,I
4558265,35.0,1999-06-27,"zink, mark",zink,mark,I
4558266,50.0,1999-10-19,"zink, mark",zink,mark,I
4558267,100.0,1999-03-29,"zinkin, benjamin",zinkin,benjamin,I
4558268,500.0,1999-10-14,"zirin, james d",zirin,james,I
4558269,250.0,1999-08-11,"zito, anthony",zito,anthony,I
4558270,99.0,1999-11-01,"zomper, j",zomper,j,I
4558271,15.0,1999-08-18,"zuckerman, michael",zuckerman,michael,I
4558272,1000.0,1999-09-28,"zurawin, iris r",zurawin,iris,I
4558273,50.0,1999-03-22,"zwart, william j",zwart,william,I
4558274,50.0,1999-10-06,"zwart, william j",zwart,william,I
4558275,100.0,1999-07-25,"zwart, william j",zwart,william,I

In [4]:
#sdf = df[df.contributor_type=='I'].sample(1000)
sdf = df[df.contributor_type=='I'].copy()
sdf

,amount,date,contributor_name,contributor_lname,contributor_fname,contributor_type
102912,180.0,2000-10-30,"JOHNSON, KENYIE PAUL",johnson,kenyie,I
103990,743.0,2000-11-07,"KIRSCH, STEVEN T",kirsch,steven,I
105298,180.0,2000-10-24,"MCCOY, TIMOTHY D",mccoy,timothy,I
105344,188.0,2000-09-04,"WILLIAMS, VICTOR K",williams,victor,I
105577,211.0,2000-11-04,"ELDER, CHESTER H",elder,chester,I
105659,13000.0,2000-10-19,"MACARTHUR, GREG",macarthur,greg,I
105665,13972.0,2000-10-13,"ABELE, CHRIS",abele,chris,I
105829,15000.0,2000-10-31,"PRICE, SOL",price,sol,I
106029,13600.0,2000-11-07,"KIRSCH, STEVEN T",kirsch,steven,I
106150,22146.0,2000-11-07,"KIRSCH, STEVEN T",kirsch,steven,I
106690,813.0,2000-10-19,"SHAPP, RICHARD A",shapp,richard,I
107082,949.0,2000-09-04,"WILLIAMS, VICTOR K",williams,victor,I
109127,1717.0,2000-11-04,"HELFRICK, EDWARD W",helfrick,edward,I
109266,8.0,2000-10-23,"MCCOY, TIMOTHY D",mccoy,timothy,I
109541,24150.0,2000-11-07,"KIRSCH, STEVEN T",kirsch,steven,I
109586,265.0,2000-11-04,"WILLIAMS, VICTOR K",williams,victor,I
109603,25750.0,2000-10-17,"SUTHERLAND, DWIGHT D JR",sutherland,dwight,I
109664,45795.0,2000-11-07,"KIRSCH, STEVEN T",kirsch,steven,I
109730,28884.0,2000-11-14,"KIRSCH, STEVEN T",kirsch,steven,I
109731,30000.0,2000-10-07,"WOODS, FRED R",woods,fred,I
109897,534000.0,2000-11-07,"KIRSCH, STEVEN T",kirsch,steven,I
109901,1000000.0,2000-10-07,"ADAMS, STEPHEN",adams,stephen,I
109921,328500.0,2000-10-19,"MACARTHUR, GREG",macarthur,greg,I
110138,322568.0,2000-11-07,"KIRSCH, STEVEN T",kirsch,steven,I
110210,56355.0,2000-11-06,"KIRSCH, STEVEN T",kirsch,steven,I
110219,87771.0,2000-11-06,"KIRSCH, STEVEN T",kirsch,steven,I
110220,87771.0,2000-11-07,"KIRSCH, STEVEN T",kirsch,steven,I
110325,1000000.0,2000-10-30,"ADAMS, STEPHEN",adams,stephen,I
110507,265.0,2000-11-04,"WILLIAMS, VICTOR K",williams,victor,I
110508,265.0,2000-11-04,"WILLIAMS, VICTOR K",williams,victor,I
...,...,...,...,...,...,...
4558246,50.0,1999-04-01,"wu, brian",wu,brian,I
4558247,150.0,1999-10-19,"wu, brian w",wu,brian,I
4558248,50.0,1999-09-22,"wyne, jamshad",wyne,jamshad,I
4558249,250.0,1999-10-20,"yaghoubi, mehrdad",yaghoubi,mehrdad,I
4558250,50.0,1999-10-23,"yassky, prof david",yassky,prof,I
4558251,50.0,1999-08-31,"yeger, eli",yeger,eli,I
4558252,125.0,1999-08-31,"yeger, itamar",yeger,itamar,I
4558253,25.0,1999-08-31,"yeger, shalom",yeger,shalom,I
4558254,20.0,1999-11-03,"yellin, gene",yellin,gene,I
4558255,50.0,1999-11-04,"yen, shawna",yen,shawna,I
4558256,70.0,1999-09-18,"yennella, maryann",yennella,maryann,I
4558257,50.0,1999-04-05,"yennella, maryann",yennella,maryann,I
4558258,100.0,1999-03-19,"yeres, jeffrey d",yeres,jeffrey,I
4558259,50.0,1999-09-22,"yost, glenn",yost,glenn,I
4558260,25.0,1999-09-21,"zacharius, alice",zacharius,alice,I
4558261,35.0,1999-10-19,"zalk, sue r",zalk,sue,I
4558262,100.0,1999-10-04,"zarin, judith ellen",zarin,judith,I
4558263,100.0,1999-10-30,"zimmer, peter k",zimmer,peter,I
4558264,75.0,1999-07-16,"zimmerman, jonathan l",zimmerman,jonathan,I
4558265,35.0,1999-06-27,"zink, mark",zink,mark,I
4558266,50.0,1999-10-19,"zink, mark",zink,mark,I
4558267,100.0,1999-03-29,"zinkin, benjamin",zinkin,benjamin,I
4558268,500.0,1999-10-14,"zirin, james d",zirin,james,I
4558269,250.0,1999-08-11,"zito, anthony",zito,anthony,I
4558270,99.0,1999-11-01,"zomper, j",zomper,j,I
4558271,15.0,1999-08-18,"zuckerman, michael",zuckerman,michael,I
4558272,1000.0,1999-09-28,"zurawin, iris r",zurawin,iris,I
4558273,50.0,1999-03-22,"zwart, william j",zwart,william,I
4558274,50.0,1999-10-06,"zwart, william j",zwart,william,I
4558275,100.0,1999-07-25,"zwart, william j",zwart,william,I

In [5]:
from clean_names import clean_name

def do_clean_name(n):
    n = str(n)
    return clean_name(n)

#sdf['clean_name'] = sdf['contributor_name'].apply(lambda c: do_clean_name(c))
#sdf

In [6]:
from ethnicolr import census_ln, pred_census_ln

Using TensorFlow backend.

In [7]:
rdf = pred_census_ln(sdf, 'contributor_lname', 2000)
rdf

,amount,date,contributor_name,contributor_lname,contributor_fname,contributor_type,race,api,black,hispanic,white
102912,180.0,2000-10-30,"JOHNSON, KENYIE PAUL",johnson,kenyie,I,white,0.004235,0.609560,0.023632,0.958353
103990,743.0,2000-11-07,"KIRSCH, STEVEN T",kirsch,steven,I,white,0.003915,0.030669,0.014547,0.976847
105298,180.0,2000-10-24,"MCCOY, TIMOTHY D",mccoy,timothy,I,white,0.010743,0.342781,0.027668,0.941825
105344,188.0,2000-09-04,"WILLIAMS, VICTOR K",williams,victor,I,white,0.001961,0.952794,0.031416,0.992903
105577,211.0,2000-11-04,"ELDER, CHESTER H",elder,chester,I,white,0.004388,0.099460,0.017577,0.980249
105659,13000.0,2000-10-19,"MACARTHUR, GREG",macarthur,greg,I,white,0.002651,0.089860,0.022709,0.862887
105665,13972.0,2000-10-13,"ABELE, CHRIS",abele,chris,I,white,0.008900,0.081121,0.037067,0.904032
105829,15000.0,2000-10-31,"PRICE, SOL",price,sol,I,white,0.004935,0.334749,0.021359,0.941375
106029,13600.0,2000-11-07,"KIRSCH, STEVEN T",kirsch,steven,I,white,0.003915,0.030669,0.014547,0.976847
106150,22146.0,2000-11-07,"KIRSCH, STEVEN T",kirsch,steven,I,white,0.003915,0.030669,0.014547,0.976847
106690,813.0,2000-10-19,"SHAPP, RICHARD A",shapp,richard,I,white,0.008674,0.103277,0.014484,0.921423
107082,949.0,2000-09-04,"WILLIAMS, VICTOR K",williams,victor,I,white,0.001961,0.952794,0.031416,0.992903
109127,1717.0,2000-11-04,"HELFRICK, EDWARD W",helfrick,edward,I,white,0.001943,0.014108,0.013088,0.990233
109266,8.0,2000-10-23,"MCCOY, TIMOTHY D",mccoy,timothy,I,white,0.010743,0.342781,0.027668,0.941825
109541,24150.0,2000-11-07,"KIRSCH, STEVEN T",kirsch,steven,I,white,0.003915,0.030669,0.014547,0.976847
109586,265.0,2000-11-04,"WILLIAMS, VICTOR K",williams,victor,I,white,0.001961,0.952794,0.031416,0.992903
109603,25750.0,2000-10-17,"SUTHERLAND, DWIGHT D JR",sutherland,dwight,I,white,0.004617,0.155920,0.019791,0.976998
109664,45795.0,2000-11-07,"KIRSCH, STEVEN T",kirsch,steven,I,white,0.003915,0.030669,0.014547,0.976847
109730,28884.0,2000-11-14,"KIRSCH, STEVEN T",kirsch,steven,I,white,0.003915,0.030669,0.014547,0.976847
109731,30000.0,2000-10-07,"WOODS, FRED R",woods,fred,I,white,0.004927,0.615952,0.032911,0.992917
109897,534000.0,2000-11-07,"KIRSCH, STEVEN T",kirsch,steven,I,white,0.003915,0.030669,0.014547,0.976847
109901,1000000.0,2000-10-07,"ADAMS, STEPHEN",adams,stephen,I,white,0.005976,0.191148,0.024831,0.967277
109921,328500.0,2000-10-19,"MACARTHUR, GREG",macarthur,greg,I,white,0.002651,0.089860,0.022709,0.862887
110138,322568.0,2000-11-07,"KIRSCH, STEVEN T",kirsch,steven,I,white,0.003915,0.030669,0.014547,0.976847
110210,56355.0,2000-11-06,"KIRSCH, STEVEN T",kirsch,steven,I,white,0.003915,0.030669,0.014547,0.976847
110219,87771.0,2000-11-06,"KIRSCH, STEVEN T",kirsch,steven,I,white,0.003915,0.030669,0.014547,0.976847
110220,87771.0,2000-11-07,"KIRSCH, STEVEN T",kirsch,steven,I,white,0.003915,0.030669,0.014547,0.976847
110325,1000000.0,2000-10-30,"ADAMS, STEPHEN",adams,stephen,I,white,0.005976,0.191148,0.024831,0.967277
110507,265.0,2000-11-04,"WILLIAMS, VICTOR K",williams,victor,I,white,0.001961,0.952794,0.031416,0.992903
110508,265.0,2000-11-04,"WILLIAMS, VICTOR K",williams,victor,I,white,0.001961,0.952794,0.031416,0.992903
...,...,...,...,...,...,...,...,...,...,...,...
4558246,50.0,1999-04-01,"wu, brian",wu,brian,I,api,0.972681,0.000213,0.000893,0.001853
4558247,150.0,1999-10-19,"wu, brian w",wu,brian,I,api,0.972681,0.000213,0.000893,0.001853
4558248,50.0,1999-09-22,"wyne, jamshad",wyne,jamshad,I,white,0.004593,0.501635,0.027987,0.985737
4558249,250.0,1999-10-20,"yaghoubi, mehrdad",yaghoubi,mehrdad,I,white,0.010594,0.024141,0.038424,0.705262
4558250,50.0,1999-10-23,"yassky, prof david",yassky,prof,I,white,0.001621,0.001716,0.009442,0.988419
4558251,50.0,1999-08-31,"yeger, eli",yeger,eli,I,white,0.004284,0.017567,0.015142,0.964631
4558252,125.0,1999-08-31,"yeger, itamar",yeger,itamar,I,white,0.004284,0.017567,0.015142,0.964631
4558253,25.0,1999-08-31,"yeger, shalom",yeger,shalom,I,white,0.004284,0.017567,0.015142,0.964631
4558254,20.0,1999-11-03,"yellin, gene",yellin,gene,I,white,0.006925,0.030023,0.029108,0.805704
4558255,50.0,1999-11-04,"yen, shawna",yen,shawna,I,api,0.959545,0.002917,0.009088,0.023935
4558256,70.0,1999-09-18,"yennella, maryann",yennella,maryann,I,white,0.009230,0.003508,0.025618,0.767812
4558257,50.0,1999-04-05,"yennella, maryann",yennella,maryann,I,white,0.009230,0.003508,0.025618,0.767812
4558258,100.0,1999-03-19,"yeres, jeffrey d",yeres,jeffrey,I,white,0.009209,0.091617,0.064599,0.750153
4558259,50.0,1999-09-22,"yost, glenn",yost,glenn,I,white,0.007192,0.024245,0.009869,0.864891
4558260,25.0,1999-09-21,"zacharius, alice",zacharius,alice,I,white,0.012208,0.254651,0.033321,0.860888
4558261,35.0,1999-10-19,"zalk, sue r",zalk,sue,I,white,0.032918,0.107236,0.023100,0.923098
4558262,100.0,1999-10-04,"zarin, judith ellen",zarin,judith,I,white,0.025848,0.024258,0.035377,0.750074
4558263,100.0,1999-10-30,"zimmer, peter k",zimmer,peter,I,white,0.002440,0.028086,0.018878,0.978265
4558264,75.0,1999-07-16,"zimmerman, jonathan l",zimmerman,jonathan,I,white,0.002021,0.016645,0.016154,0.909928
4558265,35.0,1999-06-27,"zink, mark",zink,mark,I,white,0.005032,0.017205,0.015900,0.973634
4558266,50.0,1999-10-19,"zink, mark",zink,mark,I,white,0.005032,0.017205,0.015900,0.973634
4558267,100.0,1999-03-29,"zinkin, benjamin",zinkin,benjamin,I,white,0.003762,0.015573,0.014283,0.814346
4558268,500.0,1999-10-14,"zirin, james d",zirin,james,I,white,0.007220,0.039317,0.021212,0.838545
4558269,250.0,1999-08-11,"zito, anthony",zito,anthony,I,white,0.020375,0.011151,0.017610,0.781267
4558270,99.0,1999-11-01,"zomper, j",zomper,j,I,white,0.004945,0.017107,0.015076,0.955297
4558271,15.0,1999-08-18,"zuckerman, michael",zuckerman,michael,I,white,0.001834,0.059111,0.020844,0.919681
4558272,1000.0,1999-09-28,"zurawin, iris r",zurawin,iris,I,white,0.004835,0.101312,0.028985,0.749815
4558273,50.0,1999-03-22,"zwart, william j",zwart,william,I,white,0.002406,0.020636,0.018531,0.964757
4558274,50.0,1999-10-06,"zwart, william j",zwart,william,I,white,0.002406,0.020636,0.018531,0.964757
4558275,100.0,1999-07-25,"zwart, william j",zwart,william,I,white,0.002406,0.020636,0.018531,0.964757

In [8]:
#rdf.to_csv('output-pred-contrib2000-ln.csv', index_label='idx')

### a) what proportion of contributors were black, whites, hispanics, asian etc.

In [9]:
adf = rdf.groupby(['race']).agg({'contributor_lname': 'count'})
adf *100 / adf.sum()

          contributor_lname
race
api                1.429494
black              0.164430
hispanic           2.567649
white             95.838427

### b) and proportion of total donation given by blacks, hispanics, whites, and asians.

In [10]:
bdf = rdf.groupby(['race']).agg({'amount': 'sum'})
bdf * 100 / bdf.sum()

             amount
race
api        1.546719
black      0.156275
hispanic   2.490196
white     95.806810

### c) get amount contributed by people of each race and divide it by total amount contributed.

In [11]:
contrib_white = sum(rdf.amount * rdf.white)
contrib_black = sum(rdf.amount * rdf.black)
contrib_api = sum(rdf.amount * rdf.api)
contrib_hispanic = sum(rdf.amount * rdf.hispanic)

contrib_amount = [{'race': 'white', 'amount': contrib_white},
                              {'race': 'black', 'amount': contrib_black},
                              {'race': 'api', 'amount': contrib_api},
                              {'race': 'hispanic', 'amount': contrib_hispanic}]
contrib_df = pd.DataFrame(contrib_amount, columns=['race', 'amount'])
contrib_df.amount /= 10e6
contrib_df.columns = ['race', 'amount($1M)']
contrib_df

       race  amount($1M)
0     white   153.492595
1     black    27.513028
2       api     3.688226
3  hispanic     6.871212

In [12]:
contrib_df.set_index('race', inplace=True, drop=True)
contrib_df.columns = ['% amount']
contrib_df * 100 / contrib_df.sum()

           % amount
race
white     80.125569
black     14.362237
api        1.925312
hispanic   3.586882